### ISSUE TITLE
`{props.class}` and `{props.style}` are removed when riot-meiosis dispatch is called.

### ISSUE THREAD

**Issue by steevepay** [riot-tools/meiosis#34]
The issue of https://github.com/riot-tools/meiosis/issues/32 is still happening with the latest version `4.0.0`, when I call the `store.dispatch`, it removes `props.class` and `props.style` on child components.

Here is a small Riot project to reproduce the issue: https://github.com/steevepay/riot9-issue

To test the issue, clone the Repo and install npm packages
```sh
npm install
```
Then start the Vite server:
```sh
npm run dev
```
Visit the URL vite provides.
If you take a look at the HTML source code of your web browser, the component `c-layout` is missing the class `"large"` and missing the style `"font-family: Verdana;"`

On the index.riot file, you can comment the dispatch function on line 13:
```js
// store.dispatch({ loading: true })
```
Finally the `props.class` and `props.style` are displaying the `large` and the style `"font-family: Verdana;"`.

The expected behavior is that, the `props.class` and `props.style` must be displayed even if the dispatch is executed.

**Comment by damusix** [comment]
@steevepay not sure what the props have to do with the state. The component losing the props isn't bound to state.

**Comment by steevepay** [comment]
It has been fixed with the latest version of Riot https://github.com/riot/riot/issues/3011
Thanks for your help @damusix
